{{- if .Values.enabledRBAC }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.cleanup.fullname" . }}
imagePullSecrets: 
{{ toYaml .Values.image.pullSecrets | indent 2 }}
{{- end }}
