{{- if .Values.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.cleanup.fullname" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}
        chart: {{ template "app.version" . }}
        release: {{ .Release.Name }}
      name: {{ template "app.cleanup.fullname" . }}
    spec:
      containers:
        - name: hyperkube
          image: "{{ .Values.image.hyperkube.repository }}:{{ .Values.image.hyperkube.tag }}"
          command:
            - /bin/bash
            - -c 
            - "kubectl delete svc {{ template "charts.exporter-kubelets.dnsname" . }}; exit 0;" 
      restartPolicy: OnFailure
      {{- if .Values.enabledRBAC }}
      serviceAccountName: {{ template "app.cleanup.fullname" . }}
      {{- end }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
{{- end }}