{{- if .Values.enabled }}
{{- if .Values.enabledRBAC }}
apiVersion: {{ template "rbac_api_version" . }}
kind: Role
metadata:
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: hook-succeeded
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.version" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "app.cleanup.fullname" . }}
rules:
- apiGroups:
   - ""
  resources:
  - services
  verbs: 
  - "delete"
{{- end }}
{{- end }}